### ISSUE TITLE
the keras model can not converge to a good result

### ISSUE THREAD

**Issue by KissyZhou** [lujiaying/MovieTaster-Open#3]
i have tried your keras code, looks like it can not get good model. 
1.would you mind to post some keras model results?
2.did you cut the doulist if it contains few movies. this OP may be useful?
thx in advance.

**Comment by KissyZhou** [comment]
thx for reply.
as you say, the similarity calculation can be optimized, but i think its ok.  just play it around.

**Comment by lujiaying** [comment]
OK. I'll close this issue
