### ISSUE TITLE
process2corpus() 方法keyerror

### ISSUE THREAD

**Issue by zyq11223** [lujiaying/MovieTaster-Open#9]
process2corpus() 方法keyerror

movie_name_id_dict is 130206 from [doulist_0804_09.json]
total movie is 130206 from [doulist_0804_09.json], [movie_0804_09.json]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-23-9f97d2d9d061> in <module>()
      1 if __name__ == '__main__':
----> 2   process2corpus()

1 frames
<ipython-input-22-2c03e231313d> in <listcomp>(.0)
      7             doulist_dict = json.loads(line.strip())
      8             doulist_movies = [_.encode('utf8') for _ in doulist_dict['movie_names']]
----> 9             doulist_movie_ids = [str(movie_name_id_dict[_]) for _ in doulist_movies]
     10             fwrite.write('%s\n' % ('\t'.join(doulist_movies)))
     11             fwrite_1.write('%s\n' % (' '.join(doulist_movie_ids)))

KeyError: b'\xe7\x9b\x96\xe6\x96\x87\xc2\xb7\xe6\x96\xaf\xe9\x80\x9a\xe5\xa4\x8d\xe6\xb4\xbb'

**Comment by lujiaying** [comment]
I guess it is due to the python version. I implemented this repo in Python2.7
